/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RetornoRouteImport } from './routes/retorno'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OperadoresRouteImport } from './routes/operadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmissaoRouteImport } from './routes/emissao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BalsasRouteImport } from './routes/balsas'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RetornoRoute = RetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresRoute = OperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmissaoRoute = EmissaoRouteImport.update({
  id: '/emissao',
  path: '/emissao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BalsasRoute = BalsasRouteImport.update({
  id: '/balsas',
  path: '/balsas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balsas': typeof BalsasRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emissao': typeof EmissaoRoute
  '/login': typeof LoginRoute
  '/operadores': typeof OperadoresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retorno': typeof RetornoRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balsas': typeof BalsasRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emissao': typeof EmissaoRoute
  '/login': typeof LoginRoute
  '/operadores': typeof OperadoresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retorno': typeof RetornoRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balsas': typeof BalsasRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emissao': typeof EmissaoRoute
  '/login': typeof LoginRoute
  '/operadores': typeof OperadoresRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retorno': typeof RetornoRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balsas'
    | '/catalogo'
    | '/configuracoes'
    | '/emissao'
    | '/login'
    | '/operadores'
    | '/reset-password'
    | '/retorno'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balsas'
    | '/catalogo'
    | '/configuracoes'
    | '/emissao'
    | '/login'
    | '/operadores'
    | '/reset-password'
    | '/retorno'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/balsas'
    | '/catalogo'
    | '/configuracoes'
    | '/emissao'
    | '/login'
    | '/operadores'
    | '/reset-password'
    | '/retorno'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalsasRoute: typeof BalsasRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmissaoRoute: typeof EmissaoRoute
  LoginRoute: typeof LoginRoute
  OperadoresRoute: typeof OperadoresRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RetornoRoute: typeof RetornoRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retorno': {
      id: '/retorno'
      path: '/retorno'
      fullPath: '/retorno'
      preLoaderRoute: typeof RetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores': {
      id: '/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof OperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emissao': {
      id: '/emissao'
      path: '/emissao'
      fullPath: '/emissao'
      preLoaderRoute: typeof EmissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balsas': {
      id: '/balsas'
      path: '/balsas'
      fullPath: '/balsas'
      preLoaderRoute: typeof BalsasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalsasRoute: BalsasRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmissaoRoute: EmissaoRoute,
  LoginRoute: LoginRoute,
  OperadoresRoute: OperadoresRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RetornoRoute: RetornoRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
